# Generated by Django 4.2.1 on 2023-05-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, null=True)),
                ('exel_file', models.FileField(null=True, upload_to='excelfile')),
            ],
            options={
                'db_table': 'excelfileinfotable0',
            },
        ),
    ]
