# Generated by Django 4.2.1 on 2023-05-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_studentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_admission_date', models.DateField(null=True)),
                ('student_admission_no', models.CharField(max_length=20, null=True)),
                ('student_reg_date', models.DateField(null=True)),
                ('student_reg_no', models.CharField(max_length=20, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('student_phone', models.CharField(max_length=100, null=True)),
                ('student_email', models.CharField(max_length=100, null=True)),
                ('student_address', models.CharField(max_length=200, null=True)),
                ('student_dist', models.CharField(max_length=100, null=True)),
                ('student_state', models.CharField(max_length=100, null=True)),
                ('student_company', models.CharField(max_length=100, null=True)),
                ('student_specialisation', models.CharField(max_length=100, null=True)),
                ('student_guardian_name', models.CharField(max_length=100, null=True)),
                ('student_guardian_phone', models.CharField(max_length=100, null=True)),
                ('student_enquiry_Source', models.CharField(max_length=100, null=True)),
                ('student_referral', models.CharField(max_length=100, null=True)),
                ('student_staff', models.CharField(max_length=100, null=True)),
                ('student_department', models.CharField(max_length=100, null=True)),
                ('student_Course', models.CharField(max_length=100, null=True)),
                ('student_effective_fee', models.IntegerField(max_length=100, null=True)),
                ('student_mode_training', models.CharField(max_length=100, null=True)),
                ('student_start_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'student_admission_table',
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_reg_date', models.DateField(null=True)),
                ('student_reg_no', models.CharField(max_length=20, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('student_phone', models.CharField(max_length=100, null=True)),
                ('student_email', models.CharField(max_length=100, null=True)),
                ('student_address', models.CharField(max_length=200, null=True)),
                ('student_dist', models.CharField(max_length=100, null=True)),
                ('student_state', models.CharField(max_length=100, null=True)),
                ('student_company', models.CharField(max_length=100, null=True)),
                ('student_specialisation', models.CharField(max_length=100, null=True)),
                ('student_guardian_name', models.CharField(max_length=100, null=True)),
                ('student_guardian_phone', models.CharField(max_length=100, null=True)),
                ('student_enquiry_Source', models.CharField(max_length=100, null=True)),
                ('student_referral', models.CharField(max_length=100, null=True)),
                ('student_staff', models.CharField(max_length=100, null=True)),
                ('student_department', models.CharField(max_length=100, null=True)),
                ('student_Course', models.CharField(max_length=100, null=True)),
                ('student_effective_fee', models.IntegerField(max_length=100, null=True)),
                ('student_reg_fee', models.IntegerField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'student_registration_table',
            },
        ),
        migrations.RenameModel(
            old_name='StudentInfo',
            new_name='StudentFee',
        ),
        migrations.AlterModelTable(
            name='studentfee',
            table='student_fee_table',
        ),
    ]
