# Generated by Django 4.2.1 on 2023-05-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_studentadmission_studentregistration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='student_effective_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='student_effective_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='student_reg_fee',
            field=models.IntegerField(null=True),
        ),
    ]
