# Generated by Django 4.2.1 on 2023-06-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_alter_studentadmission_student_effective_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeepaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_last_date_fee_paid', models.DateField(null=True)),
                ('student_id', models.CharField(max_length=100, null=True)),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('student_effective_fee', models.IntegerField(null=True)),
                ('student_fee_paid', models.IntegerField(null=True)),
                ('student_balance_fee', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'student_fee_paid_table',
            },
        ),
    ]
