# Generated by Django 4.2.1 on 2023-06-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_studentfeepaid_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeepaid',
            name='student_fee_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
